RentACar/ViewCompanentController/CustomerAvatarViewComponent.cs
using Business.CustomFunctions;
using Microsoft.AspNetCore.Mvc;

namespace UIWeb.ViewCompanentController
{
    public class CustomerAvatarViewComponent : ViewComponent
    {

        private readonly IHttpContextAccessor _contextAccessor;
    

        public CustomerAvatarViewComponent(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
        }

        public IViewComponentResult Invoke()
        {
            Business.CustomFunctions.UserManager manager = new UserManager(_contextAccessor);
            var claim = manager.GetUserInformations();
            ViewBag.Claims = claim;
            return View();
        }
    }
}

RentACar/Views/_Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <style>
        .avatar {
            vertical-align: middle;
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }
    </style>
    <title>DropCar &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/lib/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/lib/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/lib/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/lib/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/lib/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/lib/css/aos.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/lib/css/style.css">

</head>
<body>


    <div class="site-wrap" id="home-section">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>
    </div>
    <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
            <div class="row align-items-center position-relative">

                <div class="col-3">
                    <div class="site-logo">
                        <a href="/Home"><strong>DropCar</strong></a>
                    </div>
                </div>

                <div class="col-9  text-right">

                    <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

                    <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav ml-auto ">
                            <li class="active"><a href="/Home" class="nav-link">Ana Sayfa</a></li>
                            <li><a href="/Araba" class="nav-link">Araçlar</a></li>
                            <li><a href="/Hakkimizda" class="nav-link">Hakkımızda</a></li>
                            <li><a href="/Iletisim" class="nav-link">İletişim</a></li>

                            <li>
                                <div class="dropdown">
                                    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                                        @await Component.InvokeAsync("CustomerAvatar")
                                        <span class="caret"></span>
                                    </button>

                                    <ul class="dropdown-menu" role="menu" aria-labelledby="imageDropdown">
                                        <li role="presentation"><a role="menuitem" style="color:inherit;" tabindex="-1" href="#">Profil</a></li>
                                        <li role="presentation"><a role="menuitem" style="color:inherit;" tabindex="-1" href="#">Bagajım</a></li>
                                        <li role="presentation"><a role="menuitem" style="color:inherit;" tabindex="-1" href="#">Tüm Kiralamalarım</a></li>
                                        <li role="presentation"><a role="menuitem" style="color:inherit;" tabindex="-1" href="#">Yorumlarım</a></li>
                                        <li role="presentation"><a role="menuitem" style="color:inherit;" tabindex="-1" href="#">Favorilerim</a></li>
                                    </ul>
                                </div>
                            </li>

                        </ul>
                        
                    </nav>
                </div>

            </div>
        </div>

    </header>
    <div class="col-md-12">
        @RenderBody()
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">Hakkımızda</h2>
                    <p>2022 yılında başladığımız bu yolda konforlu ve güvenli araç filomuzla üstün hizmet ve müşteri memnuniyetini hedefleyen bir kurum olarak müşterilerimizle buluştuk. </p>
                    <ul class="list-unstyled social">
                        <li><a href="#"><span class="icon-facebook"></span></a></li>
                        <li><a href="#"><span class="icon-instagram"></span></a></li>
                        <li><a href="#"><span class="icon-twitter"></span></a></li>
                        <li><a href="#"><span class="icon-linkedin"></span></a></li>
                    </ul>
                </div>
                <div class="col-lg-8 ml-auto">
                    <div class="row">
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">Hakkımızda</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Gizlilik</a></li>
                                <li><a href="#">İletişim</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Resources</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">Hakkımızda</a></li>
                                <li><a>Basında biz</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <div class="border-top pt-5">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>.Downloaded from <a href="https://themeslab.org/" target="_blank">Themeslab</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </footer>

    <script src="~/lib/js/jquery-3.3.1.min.js"></script>
    <script src="~/lib/js/popper.min.js"></script>
    <script src="~/lib/js/bootstrap.min.js"></script>
    <script src="~/lib/js/owl.carousel.min.js"></script>
    <script src="~/lib/js/jquery.sticky.js"></script>
    <script src="~/lib/js/jquery.waypoints.min.js"></script>
    <script src="~/lib/js/jquery.animateNumber.min.js"></script>
    <script src="~/lib/js/jquery.fancybox.min.js"></script>
    <script src="~/lib/js/jquery.easing.1.3.js"></script>
    <script src="~/lib/js/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/js/aos.js"></script>

    <script src="~/lib/js/main.js"></script>

</body>
</html>